version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - C:/mongodb:/data/db

  backend:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env.production
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb

  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    container_name: frontend
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./frontend/.env.production
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
