version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - C:/mongodb:/data/db

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  admin:
    build:
      dockerfile: Dockerfile.dev
      context: ./admin/
    container_name: admin
    ports:
      - '3001:3001'
    env_file:
      - ./admin/.env.development
    volumes:
      - ./admin:/admin
      - /admin/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
